/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0070d1',
        primaryPressed: '#0064b7',
        primaryActive: '#004d8d',
        onPrimary: '#ffffff',
        linkLight: '#0064b7',
        linkDark: '#53b1ff',
        commerce: '#d53b00',
        commercePressed: '#aa2f00',
        onCommerce: '#ffffff',
        ink: '#000000',
        inkDeep: '#121314',
        inkElevated: '#181818',
        bodyLight: 'rgba(0,0,0,0.6)',
        muteLight: '#6b6b6b',
        ashLight: '#cccccc',
        bodyDark: 'rgba(255,255,255,0.7)',
        muteDark: 'rgba(229,229,229,0.55)',
        ashDark: 'rgba(229,229,229,0.2)',
        canvasLight: '#ffffff',
        surfaceSoft: '#f3f3f3',
        surfaceCard: '#f5f7fa',
        surfaceFilter: 'rgba(245,247,250,0.3)',
        canvasDark: '#000000',
        surfaceDarkElevated: '#121314',
        surfaceDarkCard: '#181818',
        hairlineLight: '#f3f3f3',
        hairlineDark: 'rgba(229,229,229,0.2)',
        onDark: '#ffffff',
        onDarkMute: '#cccccc',
        warning: '#c81b3a',
        psPlusGoldStart: '#ffce21',
        psPlusGoldMid: '#f5a623',
        psPlusGoldEnd: '#ee8e00',
        marathonYellow: '#deff20',
        deep: '#0a0f1e',
        surface: '#0a0f1e',
        elevated: '#111827',
        borderSubtle: '#1e293b',
        riskCritical: '#ef4444',
        riskHigh: '#f97316',
        riskModerate: '#eab308',
        riskLow: '#22c55e',
      },
      fontFamily: {
        display: ['Roboto', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      keyframes: {
        'fade-up': {
          '0%': { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.5s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.4s ease-out forwards',
      },
    },
    screens: {
      xs: '320px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
  },
  plugins: [],
}